apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-{{PROJECT_ID}}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api-{{PROJECT_ID}}
  template:
    metadata:
      labels:
        component: api-{{PROJECT_ID}}
    spec:
      containers:
      - name: api-{{PROJECT_ID}}
        image: {{IMAGE}}
        ports:
        - name: api-primary
          containerPort: 80
        env:
        - name: ENV
          value: prod
        - name: DATABASE_URL
          value: {{DATABASE_URL}}
---
apiVersion: v1
kind: Service
metadata:
  name: api-{{PROJECT_ID}}
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    component: api-{{PROJECT_ID}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-{{PROJECT_ID}}
  annotations:
    kubernetes.io/ingress.class: "nginx-{{PROJECT_ID}}"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-{{PROJECT_ID}}
            port:
              number: 80